/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.border.Border;
import static pos.HomeView.dishe_Payment;

/**
 *
 * @author hp
 */
public class Confirmation extends javax.swing.JFrame {
  ArrayList<Dishe> dishee=dishe_Payment;
  JLabel[] menuLabels=new JLabel[2];

    JPanel[] panels =new JPanel[6];
JLabel[] nameLabels=new JLabel[6];
                 JLabel[] priceLabels=new JLabel[6];
                 JLabel[] pricetotal=new JLabel[6];
                 JTextField[] jtext=new JTextField[6];
JTextField[] jspinner=new JTextField[6];
 Border default_border =BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (204,204,204));
    
Border yellow_border =BorderFactory.createMatteBorder(1, 1, 1, 1, new Color (255,255,255));
    /**
     * Creates new form Confirmation
     */
    public Confirmation() {
        initComponents();
     menuLabels[0]=l1; 
menuLabels[1]=l2;    
 
jtext[0]=jTextField6;  
jtext[1]=jTextField7;        
jtext[2]=jTextField8;        
jtext[3]=jTextField3;        
jtext[4]=jTextField13;        
jtext[5]=jTextField15;        

jspinner[0]=jTextField9;
jspinner[1]=jTextField10;
jspinner[2]=jTextField11;
jspinner[3]=jTextField12;
jspinner[4]=jTextField14;
jspinner[5]=jTextField16;

priceLabels[0]=lprice1;
priceLabels[1]=lprice2;
priceLabels[2]=lprice3;
priceLabels[3]=lprice4;
priceLabels[4]=lprice5;
priceLabels[5]=lprice6;

pricetotal[0]=jLabel52;
pricetotal[1]=jLabel56;
pricetotal[2]=jLabel60;
pricetotal[3]=jLabel47;
pricetotal[3]=jLabel61;
pricetotal[3]=jLabel48;

nameLabels[0]=lname1;
nameLabels[1]=lname2;
nameLabels[2]=lname3;
nameLabels[3]=lname4;
nameLabels[4]=lname5;
nameLabels[5]=lname6;

        //panel
panels[0]=jPanel12;
panels[1]=jPanel13;
panels[2]=jPanel14;
panels[3]=jPanel11;
panels[4]=jPanel15;
panels[5]=jPanel16;

showPanel();
Buy();
addActionToMenuLabels();

    }
public void showPanel(){
        for(JPanel pnl:panels)
        {
            pnl.setVisible(false);
        }
        
        
        
        
    }
public void Buy(){
    double total=0;
     for(int i=0;i<dishee.size();i++){
         
         nameLabels[i].setText(dishee.get(i).getname());
         priceLabels[i].setText(""+dishee.get(i).getprice());
         pricetotal[i].setText(""+dishee.get(i).gettotalprice());
         jspinner[i].setText(""+dishee.get(i).getquantity());
         jtext[i].setText(dishee.get(i).getnotes());
         panels[i].setVisible(true);
         total+=(dishee.get(i).getprice())*(dishee.get(i).getquantity());
         jtot.setText(""+total);
     }}
 public void Deleltd(String name){
     for(int i=0;i<dishee.size();i++){
         if(dishee.get(i).getname().equals(name)){
         dishee.remove(i);
     }}
 }
 public void setLabelBackround(JLabel label){
      for (JLabel menu : menuLabels){
          menu.setForeground(new Color(200,200,200));
      }  
          label.setForeground(new Color(255,255,255));
      }  
 public void addActionToMenuLabels(){
   Component[] components=jPanel4.getComponents();
           for(Component component:components){
               if(component instanceof JLabel ){
                   JLabel label=(JLabel) component;
                   
                   label.addMouseListener(new MouseListener() {
                       public void mouseClicked(MouseEvent e) {
                           setLabelBackround( label);
                          
                       }

                       @Override
                       public void mousePressed(MouseEvent e) {
                       }

                       @Override
                       public void mouseReleased(MouseEvent e) {
                       }

                       @Override
                       public void mouseEntered(MouseEvent e) {
                           label.setBorder(yellow_border);
                       }

                       @Override
                       public void mouseExited(MouseEvent e) {
                           label.setBorder(default_border);

                       }
                   });
                   
               }
                   }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jtot = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lname1 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        lprice1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lname2 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        lprice2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        lname3 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        lprice3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lname4 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lprice4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        lname5 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        lprice5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        lname6 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        lprice6 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 18, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmation");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 170, 50);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("Sub total");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(20, 610, 100, 32);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("#34562");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(80, 130, 70, 30);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 560, 370, 20);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 370, 20);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("Orders");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(20, 130, 80, 32);

        jtot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtot.setForeground(new java.awt.Color(255, 255, 255));
        jtot.setText("0");
        jtot.setToolTipText("");
        jPanel1.add(jtot);
        jtot.setBounds(320, 610, 60, 40);

        jButton3.setBackground(new java.awt.Color(12, 18, 62));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-64.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 10, 50, 40);

        jPanel3.setBackground(new java.awt.Color(12, 18, 62));

        jPanel12.setBackground(new java.awt.Color(12, 18, 62));
        jPanel12.setLayout(null);

        lname1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname1.setForeground(new java.awt.Color(255, 255, 255));
        lname1.setText("Spicy seasoned");
        lname1.setToolTipText("");
        jPanel12.add(lname1);
        lname1.setBounds(80, 0, 140, 50);

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 204));
        jLabel52.setText("$2.29");
        jLabel52.setToolTipText("");
        jPanel12.add(jLabel52);
        jLabel52.setBounds(310, 10, 60, 40);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(74, 88, 146));
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setToolTipText("");
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField6.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField6.setName(""); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField6);
        jTextField6.setBounds(30, 80, 250, 30);

        lprice1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice1.setForeground(new java.awt.Color(204, 204, 204));
        lprice1.setText("$2.29");
        lprice1.setToolTipText("");
        jPanel12.add(lprice1);
        lprice1.setBounds(90, 30, 80, 30);

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5);
        jButton5.setBounds(320, 70, 50, 40);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel54.setFocusCycleRoot(true);
        jPanel12.add(jLabel54);
        jLabel54.setBounds(10, 10, 60, 60);

        jTextField9.setEditable(false);
        jPanel12.add(jTextField9);
        jTextField9.setBounds(230, 40, 40, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("$");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(260, 580, 40, 50);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("$");
        jPanel12.add(jLabel21);
        jLabel21.setBounds(260, 570, 40, 60);

        jPanel13.setBackground(new java.awt.Color(12, 18, 62));
        jPanel13.setLayout(null);

        lname2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname2.setForeground(new java.awt.Color(255, 255, 255));
        lname2.setText("Spicy seasoned");
        lname2.setToolTipText("");
        jPanel13.add(lname2);
        lname2.setBounds(80, 0, 140, 50);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 204, 204));
        jLabel56.setText("$2.29");
        jLabel56.setToolTipText("");
        jPanel13.add(jLabel56);
        jLabel56.setBounds(310, 10, 60, 40);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(74, 88, 146));
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setToolTipText("");
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField7.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField7.setName(""); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField7);
        jTextField7.setBounds(30, 80, 250, 30);

        lprice2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice2.setForeground(new java.awt.Color(204, 204, 204));
        lprice2.setText("$2.29");
        lprice2.setToolTipText("");
        jPanel13.add(lprice2);
        lprice2.setBounds(90, 30, 80, 30);

        jButton6.setBackground(new java.awt.Color(153, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton6);
        jButton6.setBounds(320, 70, 50, 40);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel58.setFocusCycleRoot(true);
        jPanel13.add(jLabel58);
        jLabel58.setBounds(10, 10, 60, 60);

        jTextField10.setEditable(false);
        jPanel13.add(jTextField10);
        jTextField10.setBounds(230, 40, 40, 30);

        jPanel14.setBackground(new java.awt.Color(12, 18, 62));
        jPanel14.setLayout(null);

        lname3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname3.setForeground(new java.awt.Color(255, 255, 255));
        lname3.setText("Spicy seasoned");
        lname3.setToolTipText("");
        jPanel14.add(lname3);
        lname3.setBounds(80, 0, 140, 50);

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 204, 204));
        jLabel60.setText("$2.29");
        jLabel60.setToolTipText("");
        jPanel14.add(jLabel60);
        jLabel60.setBounds(310, 10, 60, 40);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(74, 88, 146));
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setToolTipText("");
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField8.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField8.setName(""); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel14.add(jTextField8);
        jTextField8.setBounds(30, 80, 250, 30);

        lprice3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice3.setForeground(new java.awt.Color(204, 204, 204));
        lprice3.setText("$2.29");
        lprice3.setToolTipText("");
        jPanel14.add(lprice3);
        lprice3.setBounds(90, 30, 80, 30);

        jButton7.setBackground(new java.awt.Color(153, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton7);
        jButton7.setBounds(320, 70, 50, 40);

        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel62.setFocusCycleRoot(true);
        jPanel14.add(jLabel62);
        jLabel62.setBounds(10, 10, 60, 60);

        jTextField11.setEditable(false);
        jPanel14.add(jTextField11);
        jTextField11.setBounds(230, 40, 40, 30);

        jPanel11.setBackground(new java.awt.Color(12, 18, 62));
        jPanel11.setLayout(null);

        lname4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname4.setForeground(new java.awt.Color(255, 255, 255));
        lname4.setText("Spicy seasoned");
        lname4.setToolTipText("");
        jPanel11.add(lname4);
        lname4.setBounds(90, 0, 140, 50);

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("$2.29");
        jLabel47.setToolTipText("");
        jPanel11.add(jLabel47);
        jLabel47.setBounds(310, 10, 60, 40);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(74, 88, 146));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setToolTipText("");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField3.setName(""); // NOI18N
        jPanel11.add(jTextField3);
        jTextField3.setBounds(30, 80, 250, 30);

        lprice4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice4.setForeground(new java.awt.Color(204, 204, 204));
        lprice4.setText("$2.29");
        lprice4.setToolTipText("");
        jPanel11.add(lprice4);
        lprice4.setBounds(90, 30, 80, 30);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton4);
        jButton4.setBounds(320, 70, 50, 40);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel49.setFocusCycleRoot(true);
        jPanel11.add(jLabel49);
        jLabel49.setBounds(10, 10, 60, 60);

        jTextField12.setEditable(false);
        jPanel11.add(jTextField12);
        jTextField12.setBounds(230, 40, 40, 30);

        jPanel15.setBackground(new java.awt.Color(12, 18, 62));
        jPanel15.setLayout(null);

        lname5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname5.setForeground(new java.awt.Color(255, 255, 255));
        lname5.setText("Spicy seasoned");
        lname5.setToolTipText("");
        jPanel15.add(lname5);
        lname5.setBounds(80, 0, 140, 50);

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 204, 204));
        jLabel61.setText("$2.29");
        jLabel61.setToolTipText("");
        jPanel15.add(jLabel61);
        jLabel61.setBounds(310, 10, 60, 40);

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(74, 88, 146));
        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setToolTipText("");
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField13.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField13.setName(""); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextField13);
        jTextField13.setBounds(30, 80, 250, 30);

        lprice5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice5.setForeground(new java.awt.Color(204, 204, 204));
        lprice5.setText("$2.29");
        lprice5.setToolTipText("");
        jPanel15.add(lprice5);
        lprice5.setBounds(90, 30, 80, 30);

        jButton8.setBackground(new java.awt.Color(153, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton8);
        jButton8.setBounds(320, 70, 50, 40);

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel63.setFocusCycleRoot(true);
        jPanel15.add(jLabel63);
        jLabel63.setBounds(10, 10, 60, 60);

        jTextField14.setEditable(false);
        jPanel15.add(jTextField14);
        jTextField14.setBounds(230, 40, 40, 30);

        jPanel16.setBackground(new java.awt.Color(12, 18, 62));
        jPanel16.setLayout(null);

        lname6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname6.setForeground(new java.awt.Color(255, 255, 255));
        lname6.setText("Spicy seasoned");
        lname6.setToolTipText("");
        jPanel16.add(lname6);
        lname6.setBounds(90, 0, 140, 50);

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 204, 204));
        jLabel48.setText("$2.29");
        jLabel48.setToolTipText("");
        jPanel16.add(jLabel48);
        jLabel48.setBounds(310, 10, 60, 40);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(74, 88, 146));
        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setToolTipText("");
        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField15.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextField15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField15.setName(""); // NOI18N
        jPanel16.add(jTextField15);
        jTextField15.setBounds(30, 80, 250, 30);

        lprice6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lprice6.setForeground(new java.awt.Color(204, 204, 204));
        lprice6.setText("$2.29");
        lprice6.setToolTipText("");
        jPanel16.add(lprice6);
        lprice6.setBounds(90, 30, 80, 30);

        jButton9.setBackground(new java.awt.Color(153, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton9);
        jButton9.setBounds(320, 70, 50, 40);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel51.setFocusCycleRoot(true);
        jPanel16.add(jLabel51);
        jLabel51.setBounds(10, 10, 60, 60);

        jTextField16.setEditable(false);
        jPanel16.add(jTextField16);
        jTextField16.setBounds(230, 40, 40, 30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 390, 380);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("$");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(280, 600, 40, 60);

        jPanel2.setBackground(new java.awt.Color(12, 18, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 160, 330, 20);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("2 payment methid available");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(20, 130, 200, 32);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Payment Method");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 190, 220, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Payment");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 80, 170, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 320, 40, 14);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField1);
        jTextField1.setBounds(20, 340, 310, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Card Number");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 390, 110, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField2);
        jTextField2.setBounds(20, 420, 310, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 470, 40, 14);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField4);
        jTextField4.setBounds(20, 500, 120, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CVV");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(200, 480, 40, 14);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 500, 140, 30);

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 570, 300, 10);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirm");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(180, 620, 150, 40);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 620, 140, 40);

        jPanel4.setBackground(new java.awt.Color(12, 18, 62));
        jPanel4.setLayout(null);

        l2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(204, 204, 204));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Cash");
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.add(l2);
        l2.setBounds(120, 10, 90, 50);

        l1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Credit Card");
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.add(l1);
        l1.setBounds(0, 10, 90, 50);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 230, 220, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        String card=jTextField2.getText();
        String date=jTextField4.getText();
        String cvv=jTextField5.getText();

        if(name.equals("")||card.equals("")||date.equals("")||cvv.equals("")){
         String message = "Fill in all card information!";
        JOptionPane.showMessageDialog(null, message);}
        else{
            for(int i=0;i<dishee.size();i++){
                 dishee.remove(i);
        }
            JOptionPane.showMessageDialog(null, "Payment confirmed successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
                 
                showPanel();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         for(int i=0;i<dishe_Payment.size();i++){
                 dishe_Payment.remove(i);
        }
        new HomeView().setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Deleltd(lname1.getText());
       showPanel();
                  Buy();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 Deleltd(lname2.getText());
       showPanel();
                  Buy();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 Deleltd(lname3.getText());
       showPanel();
                  Buy();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         for(int i=0;i<dishee.size();i++){
                 dishee.remove(i);
        }
        new HomeView().setVisible(true);
                    setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Deleltd(lname5.getText());
       showPanel();
                  Buy();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Deleltd(lname4.getText());
       showPanel();
                  Buy();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Deleltd(lname6.getText());
       showPanel();
                  Buy();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jtot;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel lname1;
    private javax.swing.JLabel lname2;
    private javax.swing.JLabel lname3;
    private javax.swing.JLabel lname4;
    private javax.swing.JLabel lname5;
    private javax.swing.JLabel lname6;
    private javax.swing.JLabel lprice1;
    private javax.swing.JLabel lprice2;
    private javax.swing.JLabel lprice3;
    private javax.swing.JLabel lprice4;
    private javax.swing.JLabel lprice5;
    private javax.swing.JLabel lprice6;
    // End of variables declaration//GEN-END:variables
}
