/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pos;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import static pos.HomeView.Order;

/**
 *
 * @author hp
 */
public class Management extends javax.swing.JFrame {

JTextField[] jtext=new JTextField[5];
JTextField[] jtext2=new JTextField[5];
    JPanel[] panels =new JPanel[5];

JLabel[] menuLabels=new JLabel[5];
Border default_border =BorderFactory.createMatteBorder(0, 0, 1, 0, new Color (242,242,242));
    
Border yellow_border =BorderFactory.createMatteBorder(0, 0, 1, 0, new Color (255,153,51));
    /** Creates new form Management */
    public Management() {
        initComponents();
        menuLabels[0]=l1; 
menuLabels[1]=l2; 
menuLabels[2]=l3; 
menuLabels[3]=l4; 
menuLabels[4]=l5;

jtext[0]=t1;  
jtext[1]=t2;        
jtext[2]=t3;        
jtext[3]=t5; 
jtext[4]=t4; 


jtext2[0]=tp1;  
jtext2[1]=tp2;        
jtext2[2]=tp3;        
jtext2[3]=tp5; 
jtext2[4]=tp4; 

panels[0]=jPanel19;
panels[1]=jPanel18;
panels[2]=jPanel21;
panels[3]=jPanel22;
panels[4]=jPanel17;



addActionToMenuLabels();

showPanel();
add();

    }
    public void showPanel(){
        for(JPanel pnl:panels)
        {
            pnl.setVisible(false);
        }}
public void setLabelBackround(JLabel label){
      for (JLabel menu : menuLabels){
          menu.setForeground(Color.WHITE);
      }  
          label.setForeground(new Color(255,153,51));
      }  
public void addActionToMenuLabels(){
   Component[] components=jPanel7.getComponents();
           for(Component component:components){
               if(component instanceof JLabel ){
                   JLabel label=(JLabel) component;
                   
                   label.addMouseListener(new MouseListener() {
                       public void mouseClicked(MouseEvent e) {
                           setLabelBackround( label);
                          
                       }

                       @Override
                       public void mousePressed(MouseEvent e) {
                       }

                       @Override
                       public void mouseReleased(MouseEvent e) {
                       }

                       @Override
                       public void mouseEntered(MouseEvent e) {
                           label.setBorder(yellow_border);
                       }

                       @Override
                       public void mouseExited(MouseEvent e) {
                           label.setBorder(default_border);

                       }
                   });
                   
               }
                   }
    }
public void add(){
     
     for(int i=0;i<Order.size();i++){
         
         jtext[i].setText(Order.get(i).getname());
         jtext2[i].setText(""+Order.get(i).getprice());
         panels[i].setVisible(true);
     }}
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        tp4 = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        tp2 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        tp1 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tn = new javax.swing.JTextField();
        tpn = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        tp3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        tp5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(51, 0, 51));
        jPanel7.setLayout(null);

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Grill");
        l3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l3);
        l3.setBounds(230, 10, 110, 50);

        l4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("Cold Dishes");
        l4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l4);
        l4.setBounds(340, 10, 103, 50);

        l5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("Soup");
        l5.setToolTipText("");
        l5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l5);
        l5.setBounds(440, 10, 120, 50);

        l2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Appetizer");
        l2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l2);
        l2.setBounds(140, 10, 103, 50);

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 153, 51));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Hot Dishes ");
        l1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l1);
        l1.setBounds(0, 10, 140, 50);

        l6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setToolTipText("");
        l6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(l6);
        l6.setBounds(560, 10, 70, 50);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(10, 70, 630, 60);

        jLabel1.setBackground(new java.awt.Color(255, 153, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Products Masagement");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 16, 270, 40);

        jPanel17.setBackground(new java.awt.Color(12, 18, 62));
        jPanel17.setAutoscrolls(true);
        jPanel17.setLayout(null);

        jLabel91.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(204, 204, 204));
        jLabel91.setText("20 Bowls available");
        jLabel91.setToolTipText("");
        jPanel17.add(jLabel91);
        jLabel91.setBounds(20, 150, 140, 17);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel92.setFocusCycleRoot(true);
        jPanel17.add(jLabel92);
        jLabel92.setBounds(20, 10, 120, 80);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (2).png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton12);
        jButton12.setBounds(110, 180, 50, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("$");
        jPanel17.add(jLabel5);
        jLabel5.setBounds(0, 180, 20, 30);

        t4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel17.add(t4);
        t4.setBounds(20, 110, 130, 30);
        jPanel17.add(tp4);
        tp4.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel17);
        jPanel17.setBounds(450, 440, 160, 220);

        jPanel18.setBackground(new java.awt.Color(12, 18, 62));
        jPanel18.setAutoscrolls(true);
        jPanel18.setLayout(null);

        jLabel95.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(204, 204, 204));
        jLabel95.setText("20 Bowls available");
        jLabel95.setToolTipText("");
        jPanel18.add(jLabel95);
        jLabel95.setBounds(20, 150, 140, 17);

        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel96.setFocusCycleRoot(true);
        jPanel18.add(jLabel96);
        jLabel96.setBounds(20, 10, 120, 80);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (2).png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton14);
        jButton14.setBounds(110, 180, 50, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("$");
        jPanel18.add(jLabel9);
        jLabel9.setBounds(0, 180, 20, 30);

        t2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel18.add(t2);
        t2.setBounds(20, 110, 130, 30);
        jPanel18.add(tp2);
        tp2.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel18);
        jPanel18.setBounds(450, 170, 160, 220);

        jPanel19.setBackground(new java.awt.Color(12, 18, 62));
        jPanel19.setAutoscrolls(true);
        jPanel19.setLayout(null);

        jLabel97.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(204, 204, 204));
        jLabel97.setText("20 Bowls available");
        jLabel97.setToolTipText("");
        jPanel19.add(jLabel97);
        jLabel97.setBounds(20, 150, 140, 17);

        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel98.setFocusCycleRoot(true);
        jPanel19.add(jLabel98);
        jLabel98.setBounds(20, 10, 120, 80);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (2).png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton15);
        jButton15.setBounds(110, 180, 50, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("$");
        jPanel19.add(jLabel10);
        jLabel10.setBounds(0, 180, 20, 30);

        t1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel19.add(t1);
        t1.setBounds(20, 110, 130, 30);

        tp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp1ActionPerformed(evt);
            }
        });
        jPanel19.add(tp1);
        tp1.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel19);
        jPanel19.setBounds(230, 170, 160, 220);

        jPanel20.setBackground(new java.awt.Color(12, 18, 62));
        jPanel20.setAutoscrolls(true);
        jPanel20.setLayout(null);

        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(204, 204, 204));
        jLabel99.setText("20 Bowls available");
        jLabel99.setToolTipText("");
        jPanel20.add(jLabel99);
        jLabel99.setBounds(20, 150, 140, 17);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel100.setFocusCycleRoot(true);
        jPanel20.add(jLabel100);
        jLabel100.setBounds(20, 10, 120, 80);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton16);
        jButton16.setBounds(110, 180, 50, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("$");
        jPanel20.add(jLabel11);
        jLabel11.setBounds(0, 180, 20, 30);

        tn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel20.add(tn);
        tn.setBounds(20, 110, 130, 30);
        jPanel20.add(tpn);
        tpn.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel20);
        jPanel20.setBounds(10, 170, 160, 220);

        jPanel21.setBackground(new java.awt.Color(12, 18, 62));
        jPanel21.setAutoscrolls(true);
        jPanel21.setLayout(null);

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(204, 204, 204));
        jLabel101.setText("20 Bowls available");
        jLabel101.setToolTipText("");
        jPanel21.add(jLabel101);
        jLabel101.setBounds(20, 150, 140, 17);

        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel102.setFocusCycleRoot(true);
        jPanel21.add(jLabel102);
        jLabel102.setBounds(20, 10, 120, 80);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (2).png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton17);
        jButton17.setBounds(110, 180, 50, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("$");
        jPanel21.add(jLabel12);
        jLabel12.setBounds(0, 180, 20, 30);

        t3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel21.add(t3);
        t3.setBounds(20, 110, 130, 30);
        jPanel21.add(tp3);
        tp3.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel21);
        jPanel21.setBounds(10, 440, 160, 220);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Changes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 680, 190, 50);

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 51));
        jButton2.setText("Discard Changes");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(220, 680, 190, 50);

        jPanel22.setBackground(new java.awt.Color(12, 18, 62));
        jPanel22.setAutoscrolls(true);
        jPanel22.setLayout(null);

        jLabel93.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(204, 204, 204));
        jLabel93.setText("20 Bowls available");
        jLabel93.setToolTipText("");
        jPanel22.add(jLabel93);
        jLabel93.setBounds(20, 150, 140, 17);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/food3.jpg"))); // NOI18N
        jLabel94.setFocusCycleRoot(true);
        jPanel22.add(jLabel94);
        jLabel94.setBounds(20, 10, 120, 80);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit (2).png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton13);
        jButton13.setBounds(110, 180, 50, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");
        jPanel22.add(jLabel6);
        jLabel6.setBounds(0, 180, 20, 30);

        t5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel22.add(t5);
        t5.setBounds(20, 110, 130, 30);
        jPanel22.add(tp5);
        tp5.setBounds(20, 182, 40, 30);

        jPanel1.add(jPanel22);
        jPanel22.setBounds(220, 440, 160, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     if(t4.getText().equals("")||tp4.getText().equals("")){
          String message = "Fill in all Dishe information";
        JOptionPane.showMessageDialog(null, message);  
        }
        else{
        Order.get(4).setname(t4.getText());
                                  double price1=Double.parseDouble(tp4.getText());

                Order.get(4).setprice(price1);
        }    // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 if(t2.getText().equals("")||tp2.getText().equals("")){
          String message = "Fill in all Dishe information";
        JOptionPane.showMessageDialog(null, message);  
        }
        else{
        Order.get(1).setname(t2.getText());
                                  double price1=Double.parseDouble(tp2.getText());

                Order.get(1).setprice(price1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if(t1.getText().equals("")||tp1.getText().equals("")){
          String message = "Fill in all Dishe information";
        JOptionPane.showMessageDialog(null, message);  
        }
        else{
        Order.get(0).setname(t1.getText());
                                  double price1=Double.parseDouble(tp1.getText());

                Order.get(0).setprice(price1);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        double price1=Double.parseDouble(tpn.getText());

         Order di=new Order( tn.getText(),  price1);
         Order.add(di);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 if(t3.getText().equals("")||tp3.getText().equals("")){
          String message = "Fill in all Dishe information";
        JOptionPane.showMessageDialog(null, message);  
        }
        else{
        Order.get(2).setname(t3.getText());
                                  double price1=Double.parseDouble(tp3.getText());

                Order.get(2).setprice(price1);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void tp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tp1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                String message = "successfully ,it is done";
        JOptionPane.showMessageDialog(null, message);
        add();
        new HomeView().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new HomeView().setVisible(true);
        setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
if(t5.getText().equals("")||tp5.getText().equals("")){
          String message = "Fill in all Dishe information";
        JOptionPane.showMessageDialog(null, message);  
        }
        else{
        Order.get(3).setname(t5.getText());
                                  double price1=Double.parseDouble(tp5.getText());

                Order.get(3).setprice(price1);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField tn;
    private javax.swing.JTextField tp1;
    private javax.swing.JTextField tp2;
    private javax.swing.JTextField tp3;
    private javax.swing.JTextField tp4;
    private javax.swing.JTextField tp5;
    private javax.swing.JTextField tpn;
    // End of variables declaration//GEN-END:variables

}
